# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-latest
    
    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest
      - name: Restore Nuget Packages
        run: nuget restore SkipCutscene.sln
      - name: Build
        run: |
          cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\SkipCutscene.sln /t:Build /p:Configuration=Release /p:DefineConstants=XL_NOAUTOUPDATE
      - name: Protect
        run: |
          cd "$Env:GITHUB_WORKSPACE"
          .\Lib\.NET_Reactor\dotNET_Reactor.Console.exe -file ".\SkipCutscene\bin\Release\SkipCutscene.dll" -antitamp 1 -hide_calls 1 -control_flow_obfuscation 1 -flow_level 9 -resourceencryption 1
          Move-Item -Path .\SkipCutscene\bin\Release\SkipCutscene_Secure\* -Destination .\SkipCutscene\bin\Release -Force
          Remove-Item -Path .\SkipCutscene\bin\Release\SkipCutscene_Secure\* -Force -Recurse
          Remove-Item -Path .\SkipCutscene\bin\Release\SkipCutscene -Force -Recurse
          mkdir -Path .\SkipCutscene\bin\Package\
      - name: Package
        uses: papeloto/action-zip@v1
        with:
          files: SkipCutscene\bin\Release\SkipCutscene.dll SkipCutscene\bin\Release\SkipCutscene.json SkipCutscene\bin\Release\SkipCutscene.pdb
          dest: SkipCutscene\bin\Package\latest.zip
      - name: Package
        run: |
          cd "$Env:GITHUB_WORKSPACE"
          Copy-Item -Path .\SkipCutscene\bin\Release\SkipCutscene.json -Destination .\SkipCutscene\bin\Package\
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SkipCutscene
          path: ${{ github.workspace }}\SkipCutscene\bin\Release\
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: ${{ github.workspace }}\SkipCutscene\bin\Package\
